language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev

script: php tests/tests.php

notifications:
   on_success: never
   on_failure: never