language: php

php:
  - 7.2
  - 5.6
  - 5.4

before_script:
 - if [ -n "$GITHUB_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_TOKEN}; fi;
 - composer install --prefer-dist --no-interaction --no-dev

after_failure:
  # - cat php_errors.log
  # - php -i

script: php -d display_errors=on tests/curl.php

notifications:
   on_success: never
   on_failure: never