language: php

php:
  - 5.6
  - 7.2

before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --no-dev

after_failure:
  - cat /tmp/php-error.log

script: php tests/tests.php

notifications:
   on_success: never
   on_failure: never